
services:
  backend:
    build: ./backend
    environment:
      DB_URL: postgresql+psycopg2://app_gallery:${APP_DB_PASSWORD}@pg:5432/app_gallery
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    expose: ["8000"]
    networks: [webnet, dbnet]
    labels:
      - traefik.enable=true
      - traefik.docker.network=webnet
      - traefik.http.routers.${APP_NAME}-api.rule=Host(`${APP_DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.routers.${APP_NAME}-api.entrypoints=websecure  
      - traefik.http.routers.${APP_NAME}-api.priority=100
      - traefik.http.routers.${APP_NAME}-api.tls.certresolver=cf  
      - traefik.http.services.${APP_NAME}-api.loadbalancer.server.port=8000
    restart: unless-stopped

  frontend:
    build: ./frontend
    command: sh -lc "if [ ! -d node_modules ]; then npm ci; fi; npm run dev -- --host --port 5173"
    environment:
      - VITE_API_BASE=https://${APP_DOMAIN}  
      - VITE_ALLOWED_HOSTS=${APP_DOMAIN}
      - VITE_HMR_HOST=${APP_DOMAIN}
      - VITE_HMR_PORT=443
      - VITE_HMR_PROTOCOL=wss
    expose: ["5173"]
    networks: [webnet]
    labels:
      - traefik.enable=true
      - traefik.docker.network=webnet
      - traefik.http.routers.${APP_NAME}-web.rule=Host(`${APP_DOMAIN}`) && !PathPrefix(`/api`)
      - traefik.http.routers.${APP_NAME}-web.entrypoints=websecure 
      - traefik.http.routers.${APP_NAME}-web.tls.certresolver=cf 
      - traefik.http.routers.${APP_NAME}-web.priority=10
      - traefik.http.services.${APP_NAME}-web.loadbalancer.server.port=5173
    restart: unless-stopped


networks:
  webnet: { external: true }
  dbnet:  { external: true }
